/* constants/agents.js — TrustBox
   Seed agent data for the marketplace.
   In production these come from AgentMarketplace.sol on Fuji.
   ─────────────────────────────────────────────────────── */

export const SEED_AGENTS = [
  {
    id:            "agt_sec_001",
    name:          "ShieldScan Pro",
    operator:      "Nexus Security Labs",
    version:       "v2.4.1",
    teeProvider:   "Phala Network (Intel SGX)",
    capabilities:  ["static-analysis","dependency-audit","secret-detection","reentrancy"],
    languages:     ["Solidity","Python","JavaScript","Rust","Go"],
    auditCount:    1_847,
    avgScore:      91,
    stake:         "500 AVAX",
    responseTime:  "~45s",
    encPubKey:     "0x04a3b2c1...", /* placeholder */
    teeEndpoint:   "https://phat.phala.network/contracts/0xabc123",
    status:        "online",
    accentVar:     "--c-blue",
    badge:         "Verified TEE",
  },
  {
    id:            "agt_sec_002",
    name:          "VaultAudit",
    operator:      "ChainGuard Protocol",
    version:       "v1.9.0",
    teeProvider:   "Phala Network (Intel SGX)",
    capabilities:  ["static-analysis","formal-verification","gas-optimisation","access-control"],
    languages:     ["Solidity","Vyper","Move"],
    auditCount:    934,
    avgScore:      88,
    stake:         "300 AVAX",
    responseTime:  "~60s",
    encPubKey:     "0x04d5e6f7...",
    teeEndpoint:   "https://phat.phala.network/contracts/0xdef456",
    status:        "online",
    accentVar:     "--c-teal",
    badge:         "Verified TEE",
  },
  {
    id:            "agt_sec_003",
    name:          "ZeroTrace",
    operator:      "Stealth Audit DAO",
    version:       "v3.1.2",
    teeProvider:   "Phala Network (Intel SGX)",
    capabilities:  ["secret-detection","ip-theft-prevention","licence-compliance","obfuscation-check"],
    languages:     ["JavaScript","TypeScript","Python","Java","C++"],
    auditCount:    412,
    avgScore:      94,
    stake:         "750 AVAX",
    responseTime:  "~30s",
    encPubKey:     "0x04a1b2c3...",
    teeEndpoint:   "https://phat.phala.network/contracts/0xghi789",
    status:        "online",
    accentVar:     "--c-purple",
    badge:         "Top Rated",
  },
  {
    id:            "agt_sec_004",
    name:          "DeepSec AI",
    operator:      "Autonomous Audit Inc.",
    version:       "v1.2.0",
    teeProvider:   "Phala Network (Intel SGX)",
    capabilities:  ["ai-vulnerability-detection","pattern-matching","behaviour-analysis"],
    languages:     ["Python","Rust","Go","Solidity"],
    auditCount:    267,
    avgScore:      86,
    stake:         "200 AVAX",
    responseTime:  "~90s",
    encPubKey:     "0x04f8e9d0...",
    teeEndpoint:   "https://phat.phala.network/contracts/0xjkl012",
    status:        "busy",
    accentVar:     "--c-amber",
    badge:         "AI-Powered",
  },
  {
    id:            "agt_sec_005",
    name:          "PrivacyGuard",
    operator:      "Zero-Knowledge Labs",
    version:       "v2.0.1",
    teeProvider:   "Phala Network (Intel SGX)",
    capabilities:  ["privacy-analysis","data-leak-detection","gdpr-compliance","zk-readiness"],
    languages:     ["Circom","Noir","JavaScript","Python"],
    auditCount:    183,
    avgScore:      97,
    stake:         "1000 AVAX",
    responseTime:  "~120s",
    encPubKey:     "0x04c3d4e5...",
    teeEndpoint:   "https://phat.phala.network/contracts/0xmno345",
    status:        "online",
    accentVar:     "--c-pink",
    badge:         "ZK Specialist",
  },
];

/* Capability tag colours */
export const CAPABILITY_COLORS = {
  "static-analysis":       "#52b6ff",
  "dependency-audit":      "#00e5c0",
  "secret-detection":      "#ff4d6a",
  "reentrancy":            "#ffb347",
  "formal-verification":   "#a78bfa",
  "gas-optimisation":      "#00e5c0",
  "access-control":        "#52b6ff",
  "ip-theft-prevention":   "#ff6eb4",
  "licence-compliance":    "#ffb347",
  "obfuscation-check":     "#a78bfa",
  "ai-vulnerability-detection": "#52b6ff",
  "pattern-matching":      "#00e5c0",
  "behaviour-analysis":    "#a78bfa",
  "privacy-analysis":      "#ff6eb4",
  "data-leak-detection":   "#ff4d6a",
  "gdpr-compliance":       "#00e5c0",
  "zk-readiness":          "#a78bfa",
};
